# WARN: This is supposed to be used for development only for using the db without a server. On linux, make sure your user can use docker without root permissions.

services:
  mongo1:
    container_name: mongo1
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "dev_mongo1_data:/data/db"
      - "dev_mongo1_config:/data/configdb"
      - "./replica.key:/data/replica.key"
    environment:
      - MONGO_INITDB_DATABASE=maharajamart
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:?error}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:?error}
      - MONGO_REPLICA_SET_NAME=rs0
      - MONGODB_ADVERTISED_HOSTNAME=127.0.0.1
    command:
      [
        "--replSet",
        "rs0",
        "--bind_ip_all",
        "--port",
        "27017",
        "--keyFile",
        "/data/replica.key",
      ]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
  mongo2:
    container_name: mongo2
    image: mongo
    ports:
      - "27018:27018"
    volumes:
      - "dev_mongo2_data:/data/db"
      - "dev_mongo2_config:/data/configdb"
      - "./replica.key:/data/replica.key"
    environment:
      - MONGO_INITDB_DATABASE=maharajamart
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:?error}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:?error}
      - MONGO_REPLICA_SET_NAME=rs0
      - MONGODB_ADVERTISED_HOSTNAME=127.0.0.1
    command:
      [
        "--replSet",
        "rs0",
        "--bind_ip_all",
        "--port",
        "27018",
        "--keyFile",
        "/data/replica.key",
      ]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
  mongo3:
    container_name: mongo3
    image: mongo
    ports:
      - "27019:27019"
    volumes:
      - "dev_mongo3_data:/data/db"
      - "dev_mongo3_config:/data/configdb"
      - "./replica.key:/data/replica.key"
    environment:
      - MONGO_INITDB_DATABASE=maharajamart
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:?error}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:?error}
      - MONGO_REPLICA_SET_NAME=rs0
      - MONGODB_ADVERTISED_HOSTNAME=127.0.0.1
    command:
      [
        "--replSet",
        "rs0",
        "--bind_ip_all",
        "--port",
        "27019",
        "--keyFile",
        "/data/replica.key",
      ]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
  mongodb-init:
    image: mongo
    container_name: mongodb-init
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: bash -c "chmod +x init-replica-set.sh && ./init-replica-set.sh"
    volumes:
      - "./init-replica-set.dev.sh:/init-replica-set.sh"
      - "./.env:/.env"
    restart: "no" # WHY IN THE WORLD IS THIS SUPPOSED TO BE A STRING????? EVERY OTHER VALUE ISN'T

volumes:
  dev_mongo1_data:
  dev_mongo2_data:
  dev_mongo3_data:
  dev_mongo1_config:
  dev_mongo2_config:
  dev_mongo3_config:
